---
title: "Individual Project"
---

```{r, echo=FALSE, include=FALSE}
library(kableExtra)
library(knitr)
library(tidyverse)
```


# Learning Objectives

- identify interesting hypotheses to evaluate in your own data
- gain experience selecting appropriate statistical methods and writing an analysis plan that directly addresses your hypotheses
- gain experience communicating statistical findings in writing and in an oral presentation

# Case Study Goals

- analyze data and interpret findings of your own study 
- effectively communicate results of your analysis to your peers using compelling graphical displays and text



# Data 

Students seeking interesting datasets may wish to consider one or more of the following resources. Students may provide their own data, with the understanding that these data should not have been analyzed previously as part of a course assignment or internship (if you would like to take a prior analysis to the next level, please provide the full prior analysis write-up with your proposal for evaluation).

  - <a href="http://derekogle.com/fishR/packages#packages-of-data">fishR</a> : this is a collection of freshwater fisheries datasets
  - <a href="https://cornelllabofornithology.github.io/auk/">auk</a>: R package for downloading and reading eBird data (spatio-temporal big data with interesting reporting biases)
  - <a href="https://www.fisheries.noaa.gov/alaska/commercial-fishing/alaska-groundfish-bottom-trawl-survey-data">Alaska Fish Surveys</a>: Alaska Groundfish Bottom Trawl Survey Data (spatio-temporal data involving changing ocean temperatures and species abundance)
  - <a href="https://www.zooniverse.org/">Zooniverse</a>: Variety of cool citizen science projects (squirrels!)
  - <a href="https://www.e-butterfly.org/">eButterfly</a>: Can't get enough Lepidoptera?  Here's more!
  - <a href="https://www.cdc.gov/nchs/data_access/vitalstatsonline.htm">CDC Vital Statistics Data</a>:  All US births and deaths
  - <a href="https://guides.lib.berkeley.edu/publichealth/healthstatistics/rawdata">Berkeley Health Data Library</a>:  Variety of interesting health data worth exploring
  - <a href="https://dataverse.harvard.edu">Harvard Dataverse</a>:  Public data repository for a variety of studies
  - <a href=https://www.economicsnetwork.ac.uk/data_sets">The Economics Network</a>:  Economic data freely available online
  - <a href=https://fred.stlouisfed.org">FRED</a>:  Economic data from the St. Louis Fed
        
        
 
    
    
  



# Resources

- Duke Global Health Institute Research Data Analysis Center (RDAC) Statistical Analysis Plan Template (on Sakai): while you should not follow this format, it's helpful to look at the structure and content needed when requesting analysis from a professional statistics core, as it will help you see relevant aspects in describing data and getting information needed to craft an analysis plan.
- Structure of a Data Analysis Report by Prof. Brian Junker (on Sakai): great guide to the bones of a good project report
- [Slides on Report Writing](decks/reportintrodata.html)
- [Slides on Statistical Analysis Plans](decks/sap.html)

# Reports 

- Submission I: Aims, Introduction, and EDA, is due February 3 at 10am EDT. The submission can be no more than 3 pages (11 point font or larger -- adhere to this requirement throughout) in length. Pages past 3 will be treated as ineligible for grading. Note that in later submissions, someone else needs to reproduce your work -- so the data needs to be made available to other students.
- Submission II: Project Methods, Analysis Plan, \& Preliminary Results is due at 10am EDT on March 3.  This part should include the prior submission and be no more than 8 pages in length (same font requirement). Reproducible code/data should also be submitted. Feedback will be provided by peers and the instructional team. A comprehensive response to the reviews obtained on Submission I (with corresponding edits to your report) can be submitted to earn up to 50% of the points deducted.
- Submission III of the individual project is due at 10am EDT on April 6. This should be a final report (though revisions are allowed), with a 12 page limit. (Note you are welcome at any stage to reallocate space as long as the basic ideas still come through.) Reproducible code/data should also be submitted. Feedback will be provided by peers and the instructional team. Students who also submit a comprehensive response to reviews from Submission II along with edits incorporated in the (new) document are eligible to receive up to 50% of the deducted points back from Submission II (this does not include reproducibility points).
- Each student will present the project in class in April to get feedback and suggestions from classmates.
- Final revisions of the individual project (a final report and comprehensive reponse to reviews) are due at 10am EST on April 25. This should be the complete report of  no more than 12 pages.  Students are eligible to receive up to 50% of the deducted points (excluding reproducibility deductions) back from Submission III. 






